### ISSUE TITLE
The compiled version is fake

### ISSUE THREAD

**Issue by davidfarah2003** [heysurfer/Growtopia-GABB#2]
Dear noob, instead of trying to scam people with your stupid not well hidden nanocore RAT, you could do something useful with your life and share the actual source code of gabb for the greater good of humanity. But guess you are too retarded for that

**Comment by heysurfer** [comment]
lol its not fixed u dont know c++ shut up noob

**Comment by XDarkTitan** [comment]
ohh this is a fake?
